In [1]:
from google.colab import files
uploaded = files.upload()

Saving irrigation_data.csv to irrigation_data.csv


In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [4]:
df = pd.read_csv("irrigation_data.csv")
print("     First 5 rows of raw data:")
print(df.head())

     First 5 rows of raw data:
         Date  Rainfall_mm  Temp_C  Humidity  Soil_Moisture Crop_Type  \
0  2025-08-01            5      32        60             28     Wheat   
1  2025-08-02           20      29        75             45     Wheat   
2  2025-08-03            0      35        50             18      Rice   
3  2025-08-04           12      30        70             40      Rice   
4  2025-08-05            8      31        65             30     Maize   

        Stage Irrigation_Required  
0  Vegetative                 Yes  
1  Vegetative                  No  
2   Flowering                 Yes  
3   Flowering                  No  
4    Maturity                 Yes  


In [5]:
df = df.dropna()

In [6]:
label_encoder = LabelEncoder()
df['Crop_Type_Enc'] = label_encoder.fit_transform(df['Crop_Type'])
df['Stage_Enc'] = label_encoder.fit_transform(df['Stage'])
df['Irrigation_Enc'] = label_encoder.fit_transform(df['Irrigation_Required'])

print("\n     Encoded labels for irrigation decision:")
print(dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))



     Encoded labels for irrigation decision:
{'No': np.int64(0), 'Yes': np.int64(1)}


In [7]:
X = df[['Rainfall_mm', 'Temp_C', 'Humidity', 'Soil_Moisture', 'Crop_Type_Enc',
'Stage_Enc']]
y = df['Irrigation_Enc']

In [11]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("\nScaled feature sample:")
print(X_scaled[:5])


Scaled feature sample:
[[-0.59234888  0.29138576 -0.46499055 -0.44331035  1.06904497  1.11803399]
 [ 1.62895941 -1.16554303  1.27872403  1.35104106  1.06904497  1.11803399]
 [-1.33278497  1.74831455 -1.62746694 -1.49881117 -0.26726124 -1.11803399]
 [ 0.44426166 -0.6799001   0.69748583  0.82329065 -0.26726124 -1.11803399]
 [-0.14808722 -0.19425717  0.11624764 -0.23221018 -1.60356745  0.        ]]
